version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: academic_repo_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: academic_repo_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: academic_user
      MYSQL_PASSWORD: academic_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - academic_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: academic_repo_backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql+pymysql://academic_user:academic_pass@mysql:3306/academic_repo_db
      - SECRET_KEY=your-super-secret-key-change-this-in-production
      - DEBUG=True
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    depends_on:
      - mysql
    networks:
      - academic_network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: academic_repo_frontend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - academic_network

  # Redis (for caching - optional)
  redis:
    image: redis:7.0-alpine
    container_name: academic_repo_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - academic_network

volumes:
  mysql_data:
  redis_data:

networks:
  academic_network:
    driver: bridge
